name: Fetch Templates

on:
  schedule:
    - cron: "45 4 * * *" # Every morning at 4:45 am Central

  workflow_dispatch:

jobs:
  matrix-test:
    strategy:
       include:
         - environment: qa
           branch: main
           api-key: ${{ secrets.SENDGRID_API_KEY_QA }}
         - environment: staging
           branch: staging
           api-key: ${{ secrets.SENDGRID_API_KEY_STAGING }}
         - environment: production
           branch: production
           api-key: ${{ secrets.SENDGRID_API_KEY_PRODUCTION }}
    
    steps:
      - name: Echo site details
        env:
          BRANCH: ${{ matrix.branch }}
          ENV: ${{ matrix.environment }}
          SENDGRID_API_KEY: ${{ matrix.api-key }}
        run: echo ${BRANCH} ${ENV} ${SENDGRID_API_KEY}
