name: Get Env Var

on: [push, workflow_dispatch]

jobs:
  matrix-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - environment: "QA"
            branch-name: "main"
          - environment: "STAGING"
            branch-name: "staging"
          - environment: "PRODUCTION"
            branch-name: "production"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add environment variable
        env:
          ENV_NAME: ${{ matrix.environment }}
        run: |
          echo "SENDGRID_API_KEY=${{ secrets[format('SENDGRID_API_KEY_{0}', env.ENV_NAME)] }}" >> $GITHUB_ENV

      - name: Test environment variable
        run: echo "hell yeah"
        if: env.SENDGRID_API_KEY == 'this is the qa key'
