name: Fetch Templates

on: [push, workflow_dispatch]

jobs:
  matrix-test:
    strategy:
      matrix:
        include:
          - environment: "qa"
            branch-name: "main"
            api-key: ${{ secrets.SENDGRID_API_KEY_QA }}
          - environment: "staging"
            branch-name: "staging"
            api-key: ${{ secrets.SENDGRID_API_KEY_STAGING }}
          - environment: "production"
            branch-name: "production"
            api-key: ${{ secrets.SENDGRID_API_KEY_PRODUCTION }}
    
    steps:
      - name: Echo site details
        env:
          BRANCH_NAME: ${{ matrix.branch-name }}
          ENV_NAME: ${{ matrix.environment }}
          SENDGRID_API_KEY: ${{ matrix.api-key }}
        run: echo ${BRANCH_NAME} ${ENV_NAME} ${SENDGRID_API_KEY}
