name: Fetch Templates

on:
  schedule:
    - cron: "45 4 * * 5" # Every Friday at 4:45 am Central

  workflow_dispatch:

jobs:
  fetch-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: get-branch-name
        run: echo "::set-output name=branch-name::RC-$(date +'%Y-%m-%d')"

      - name: Checkout 'main'
        uses: actions/checkout@v2
        with:
          ref: "main"
          
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/

      - name: Fetch templates
        run: node index.js

      - name: Check for changes
        id: status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=has_changes::yes"
          fi
        working-directory: templates
        
      - name: Create branch and commit changes
        run: |
          git checkout -b ${{ steps.get-branch-name.outputs.branch-name }}
          git config --local user.email "github@jeffisrael.com"
          git config --local user.name "GitHub Workflows"
          git add templates *
          git commit templates -m "Template updates from $(date +'%Y-%m-%d')"
          git push --set-upstream origin \
            ${{ steps.get-branch-name.outputs.branch-name }}
        if: steps.status.outputs.has_changes == 'yes'      
