name: Fetch Templates

on:
  schedule:
    - cron: "45 4 * * *" # Every morning at 4:45 am Central

  workflow_dispatch:

jobs:
  fetch-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16
          registry-url: https://npm.pkg.github.com/

      - name: Fetch templates
        run: |
          yarn
          yarn run fetch
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

      - name: Check for changes
        id: status
        run: |
          if [ -n "$(git status --porcelain templates)" ]; then
            echo "::set-output name=has_changes::yes"
          fi

      - name: Get branch name
        id: get-branch-name
        run: echo "::set-output name=branch-name::templates-$(date +'%Y-%m-%d')"
        if: steps.status.outputs.has_changes == 'yes'      

      - name: Create branch and commit changes
        run: |
          git status --porcelain templates
          git checkout -b ${{ steps.get-branch-name.outputs.branch-name }}
          git config --local user.email "github@jeffisrael.com"
          git config --local user.name "GitHub Workflows"
          git add templates/*
          git commit -m "Template updates from $(date +'%Y-%m-%d')"
          git push --set-upstream origin \
            ${{ steps.get-branch-name.outputs.branch-name }}
        if: steps.status.outputs.has_changes == 'yes'      

      - name: Open a pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.get-branch-name.outputs.branch-name }}
          destination_branch: "main"
          pr_title: "Template updates from $(date +'%Y-%m-%d')"
          pr_body: "Template changes pulled via the SendGrid API"
          pr_label: "github actions"
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.status.outputs.has_changes == 'yes'      
